services:
  fastapi:
    build: ./server
    container_name: onyx-ix-guide-api
    volumes:
      - temp-audio-data:/server/temp_audio
    restart: unless-stopped
    command: uv run python -m server.main
    env_file:
      - ./server/.env
    depends_on:
      - redis

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: onyx-ix-engine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - temp-audio-data:/usr/share/nginx/html/temp-audio
    depends_on:
      - fastapi

  redis:
    image: redis:7-alpine
    container_name: onyx-ix-guide-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    command: redis-server --requirepass 36951

volumes:
  redis-data:
  temp-audio-data:
